export const SET_CHARACTERS = 'SET_CHARACTERS';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SEARCHED_CHARACTERS = 'SEARCHED_CHARACTERS';
export const SET_CHARACTER_DETAILS = 'SET_CHARACTER_DETAILS';